//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justsay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public string ShowName { get; set; }
        public System.DateTime Time { get; set; }
        public string Content { get; set; }
        public int FunnyID { get; set; }
        public int Up { get; set; }
    
        public virtual Funny Funny { get; set; }
        public virtual Member Member { get; set; }
    }
}
