//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justsay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confess
    {
        public Confess()
        {
            this.EmailQueues = new HashSet<EmailQueue>();
            this.PhoneQueues = new HashSet<PhoneQueue>();
            this.Funnies = new HashSet<Funny>();
        }
    
        public int ID { get; set; }
        public int MemberID { get; set; }
        public string ShowName { get; set; }
        public string Content { get; set; }
        public System.DateTime Time { get; set; }
        public int Up { get; set; }
        public int Click { get; set; }
        public string Message { get; set; }
        public bool IsSms { get; set; }
        public string FlashUrl { get; set; }
        public string MusicUrl { get; set; }
        public string ToEmail { get; set; }
        public string ToPhone { get; set; }
        public string ToName { get; set; }
        public string ImgUrl { get; set; }
        public string ViewName { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ICollection<EmailQueue> EmailQueues { get; set; }
        public virtual ICollection<PhoneQueue> PhoneQueues { get; set; }
        public virtual ICollection<Funny> Funnies { get; set; }
    }
}
