//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Justsay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JustSayEntities : DbContext
    {
        public JustSayEntities()
            : base("name=JustSayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionLog> ActionLogs { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Confess> Confesses { get; set; }
        public DbSet<Funny> Funnies { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Relation> Relations { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<ToDoList> ToDoLists { get; set; }
        public DbSet<EmailQueue> EmailQueues { get; set; }
        public DbSet<PhoneQueue> PhoneQueues { get; set; }
        public DbSet<Pro> Pros { get; set; }
    }
}
